function [Address] = GetYahooWebAddress(StockSymbol,...
    InitialDay, InitialMonth, InitialYear, ...
    FinalDay, FinalMonth, FinalYear)

YahooAddress = 'http://ichart.finance.yahoo.com/table.csv?';
Address = [...
    YahooAddress ...
    's=' StockSymbol ...
    '&a=' InitialMonth ...
    '&b=' InitialDay ...
    '&c=' InitialYear ...
    '&d=' FinalMonth ...
    '&e=' FinalDay ...
    '&f=' FinalYear ...
    '&g=' 'd&ignore=.csv'];